{
 "title": "DBaaS / System Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(system_uptime, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 - cpu_usage_idle{host=\"$instance\", cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "CPU Total %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu_usage_user{host=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "User"
    },
    {
     "expr": "cpu_usage_system{host=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "System"
    },
    {
     "expr": "cpu_usage_idle{host=\"$instance\", cpu=\"cpu-total\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mem_used_percent{host=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mem_used{host=\"$instance\"}",
     "legendFormat": "mem_used"
    },
    {
     "expr": "mem_buffered{host=\"$instance\"}",
     "legendFormat": "mem_buffered"
    },
    {
     "expr": "mem_cached{host=\"$instance\"}",
     "legendFormat": "mem_cached"
    },
    {
     "expr": "swap_used{host=\"$instance\"}",
     "legendFormat": "mem_swap"
    },
    {
     "expr": "mem_free{host=\"$instance\"}",
     "legendFormat": "mem_free"
    }
   ]
  },
  { "title": "Block Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$instance\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk IO Reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{host=\"$instance\",name!~\"dm-[0-9]\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(diskio_write_bytes{host=\"$instance\",name!~\"dm-[0-9]\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(diskio_io_time{host=\"$instance\"}[1m]) / 10",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=\"$instance\",interface!~\"lo\"}[1m])",
     "legendFormat": "received by the {{interface}}"
    },
    {
     "expr": "rate(net_bytes_sent{host=\"$instance\",interface!~\"lo\"}[1m])",
     "legendFormat": "sent by the {{interface}}"
    }
   ]
  }
 ]
}