name: globally-load-balanced-web-servers PR Check
on:
  pull_request:
    paths:
      - 'reference-architectures/globally-load-balanced-web-servers/**/*.tf'
      - 'reference-architectures/globally-load-balanced-web-servers/test/*'

jobs:
  call-common:
    uses: .github/workflows/workflow-terraform-pr-check.yaml
    with:
      module_path: reference-architectures/globally-load-balanced-web-servers
