name: partner-network-connect-aws PR Check
on:
  pull_request:
    paths:
      - 'reference-architectures/partner-network-connect-aws/**/*.tf'
      - 'reference-architectures/partner-network-connect-aws/test/**/*'

jobs:
  call-common:
    uses: ./.github/workflows/workflow-terraform-pr-check.yaml
    with:
      module_path: reference-architectures/partner-network-connect-aws
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.SOLUTIONS_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SOLUTIONS_AWS_SECRET_ACCESS_KEY }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.TEST_DIGITALOCEAN_ACCESS_TOKEN }}
