name: site-to-site-vpn-aws PR Check
on:
  pull_request:
    paths:
      - 'reference-architectures/site-to-site-vpn-aws/**/*.tf'
      - 'reference-architectures/site-to-site-vpn-aws/test/**/*'

jobs:
  call-common:
    uses: ./.github/workflows/workflow-terraform-pr-check.yaml
    with:
      module_path: reference-architectures/site-to-site-vpn-aws
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.TEST_DIGITALOCEAN_ACCESS_TOKEN }}
