# This is a reusable workflow called from the other workflows.
# Centralizing in this way allows us to have one place to configure our tests.
on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true

jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Install Terraform
        run: |
          TF_VERSION="1.11.4"; apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip terraform_${TF_VERSION}_linux_amd64.zip && sudo mv terraform /usr/local/bin
      - name: Run tests
        working-directory: ${{ inputs.module_path }}/test/integration
        run: |
          if [ -d "." ]; then go test ./...; else echo "No tests"; fi
