# This is a reusable workflow called from the other workflows.
# Centralizing in this way allows us to have one place to configure our tests.
on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true

jobs:
  terratest:
    name: Terratest Integration Tests
    runs-on: ubuntu-latest
    container:
      image: registry.digitalocean.com/scale-with-simplicity-test/terraform-test:latest
      credentials:
        username: solutions@digitalocean.com
        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Integration Tests
        working-directory: ${{ inputs.module_path }}
        run: make test-integration
